import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Logo } from '@/components/logo';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const currentYear = new Date().getFullYear();

export const metadata: Metadata = {
  title: 'RappelScanner',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={cn('container mx-auto px-4', inter.className)}>
        <header className="flex justify-center mt-10">
          <Logo />
        </header>
        {children}
        <footer className="flex items-center justify-center max-w-2xl mx-auto text-xs border-t py-5">
          <p>&copy; {currentYear} RappelScanner</p>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
